### ISSUE TITLE
My animation is looping

### ISSUE THREAD

**Issue by azur29** [cjgammon/SnapSVG-Animator#85] opened 2016-10-10 12:14 UTC
Hello everybody,

sorry in advance if I'm not in the right place.

I'm using animate cc 2015.2 and just create à circle like that:

under Scene 1 Frame 1 (séquence1 ->calque1: image 1):

**this.stop(); 
var s = Snap(400,400);
var circle = s.circle(90,120,80);**

The result is multiple circles on the screen.The script  seem to make à loop .

In animate CC i verifying that a looping instruction are not checking without any result.

I thing i don't understand something....

Can someOne help me ?

Sorry for my bad english
-azur-

**Comment by cjgammon** [comment] 2016-10-10 15:01
This is a duplicate of bug #75

I have a fix for this on **dev** if you replace the published `SnapSVGAnimator.js` file in your project with the one in **dev** it should fix the issue.  Also when you create a new Snap instance it will create a new SVG element rather than draw in your current stage SVG element.  You should instead call 
```this.el.circle(90,120,80);```

**Closed** 2016-10-14 13:50 UTC
Labels: bug, duplicate
